[package]
name = "phy6252-emu"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"
description = "PHY6252 Cortex-M0 chip emulator (AI-Thinker PB-03F-Kit)"
repository = "https://github.com/Pom4H/phy6252-emu"

[dependencies]
zmu_cortex_m = { path = "third_party/zmu/zmu_cortex_m", default-features = false, features = ["armv6m"] }
