#!/usr/bin/env python3
"""Rebuild the portable Saturn package from the pinned runtime and shared Rust compiler.
Requires Rust with wasm32-unknown-unknown and WASI SDK 24 (WASI_SDK_PATH).
No network access, package upload or hardware programming is performed.
"""
import base64, hashlib, json, os, pathlib, re, subprocess
root=pathlib.Path(__file__).resolve().parent.parent
package=root/'packages/saturn';dist=package/'dist';dist.mkdir(parents=True,exist_ok=True)
sdk=pathlib.Path(os.environ.get('WASI_SDK_PATH','/opt/wasi-sdk'))
source=(root/'src/controller/saturn_bridge.c').read_text()+(root/'src/controller/saturn_state.inc').read_text()
exports=sorted(set(re.findall(r'\b(fv_fbd_\w+)\s*\(',source)))
cmd=[str(sdk/'bin/clang'),'-Oz','-flto','-std=c11','-Uunix','-fwrapv','-Wno-implicit-fallthrough','-Ithird_party/fbd-runtime','-mexec-model=reactor',
     'src/controller/saturn_unit.c','third_party/fbd-runtime/fbdsun.c','-Wl,--strip-all','-Wl,--initial-memory=262144','-Wl,--max-memory=16777216',
     '-Wl,-z,stack-size=65536','-Wl,--export=malloc','-Wl,--export=free',*[f'-Wl,--export={name}' for name in exports],'-lm','-o',str(dist/'runtime.wasm')]
subprocess.run(cmd,cwd=root,check=True)
subprocess.run(['cargo','build','--locked','--offline','--manifest-path','packages/saturn-compiler/Cargo.toml','--release','--target','wasm32-unknown-unknown'],cwd=root,check=True)
compiler=root/'packages/saturn-compiler/target/wasm32-unknown-unknown/release/firmverse_saturn_compiler.wasm'
(dist/'compiler.wasm').write_bytes(compiler.read_bytes())
output='// Generated by tools/build_saturn_package.py; do not hand-edit.\n';manifest={'schema':'firmverse/saturn-package@1','upstream':'d09d459c68286fb4f84fa074b0b7a0f27371406d','assets':{}}
for name in ['compiler','runtime']:
    data=(dist/f'{name}.wasm').read_bytes();sha=hashlib.sha256(data).hexdigest()
    output+=f"export const {name}Base64 = '{base64.b64encode(data).decode()}';\nexport const {name}Hash = '{sha}';\n"
    manifest['assets'][name]={'bytes':len(data),'sha256':sha}
(package/'src').mkdir(exist_ok=True);(package/'src/binaries.ts').write_text(output)
(package/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
print(json.dumps(manifest))
